FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# RUN npm run build

COPY /public ./public

# USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "run", "dev"]
